# Generated by Django 3.1.5 on 2021-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('shipping_status', models.CharField(choices=[('pending', 'Pending'), ('out_for_deliver', 'Out for Deliver'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('added_by', models.IntegerField()),
            ],
        ),
    ]
